
name: Test Build

on:
  pull_request:

jobs:
  build:
    name: Test ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            target: x86-64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch fork upstream
        env:
            BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
              git remote add forkUpstream https://github.com/$BRANCH_NAME  # URL of the fork
              git fetch forkUpstream  # Fetch fork
